# FLP: Functional Project: Decision Trees
# Author: Matus Remen (xremen01@stud.fit.vutbr.cz)
# Date: 09.03.2024

MAIN=flp-fun

.PHONY: clean

all: $(MAIN).hs
	ghc -Wall $(MAIN).hs

clean:
	rm Src/*.hi Src/*.o *.o *.hi $(MAIN)

